/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "TASK_ID" INT NULL,
    "TASK_NAME" VARCHAR(255 char) NULL,
    "GROUP_ID" INT NULL,
    "WORKFLOW_INSTANCE_ID" INT NULL,
    "PRIORITY" INT DEFAULT 0 NULL,
    "STATUS" TINYINT DEFAULT -1 NULL,
    "FORCE_START" TINYINT DEFAULT 0 NULL,
    "IN_QUEUE" TINYINT DEFAULT 0 NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "TASK_TYPE" VARCHAR(50 char) NOT NULL,
    "TASK_EXECUTE_TYPE" INT DEFAULT 0 NULL,
    "TASK_CODE" BIGINT NOT NULL,
    "TASK_DEFINITION_VERSION" INT DEFAULT 1 NOT NULL,
    "WORKFLOW_INSTANCE_ID" INT NULL,
    "WORKFLOW_INSTANCE_NAME" VARCHAR(255 char) NULL,
    "PROJECT_CODE" BIGINT NULL,
    "STATE" TINYINT NULL,
    "SUBMIT_TIME" TIMESTAMP(0) NULL,
    "START_TIME" TIMESTAMP(0) NULL,
    "END_TIME" TIMESTAMP(0) NULL,
    "HOST" VARCHAR(135 char) NULL,
    "EXECUTE_PATH" VARCHAR(200 char) NULL,
    "LOG_PATH" CLOB NULL,
    "ALERT_FLAG" TINYINT NULL,
    "RETRY_TIMES" INT DEFAULT 0 NULL,
    "PID" INT NULL,
    "APP_LINK" TEXT NULL,
    "TASK_PARAMS" CLOB NULL,
    "FLAG" TINYINT DEFAULT 1 NULL,
    "RETRY_INTERVAL" INT NULL,
    "MAX_RETRY_TIMES" INT NULL,
    "TASK_INSTANCE_PRIORITY" INT NULL,
    "WORKER_GROUP" VARCHAR(255 char) NULL,
    "ENVIRONMENT_CODE" BIGINT DEFAULT -1 NULL,
    "ENVIRONMENT_CONFIG" TEXT NULL,
    "EXECUTOR_ID" INT NULL,
    "EXECUTOR_NAME" VARCHAR(64 char) NULL,
    "FIRST_SUBMIT_TIME" TIMESTAMP(0) NULL,
    "DELAY_TIME" INT DEFAULT 0 NULL,
    "VAR_POOL" CLOB NULL,
    "TASK_GROUP_ID" INT NULL,
    "DRY_RUN" TINYINT DEFAULT 0 NULL,
    "CPU_QUOTA" INT DEFAULT -1 NOT NULL,
    "MEMORY_MAX" INT DEFAULT -1 NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE_CONTEXT";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE_CONTEXT" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "TASK_INSTANCE_ID" INT NOT NULL,
    "TASK_INSTANCE_CONTEXT" TEXT NOT NULL,
    "CONTEXT_TYPE" VARCHAR(200 char) NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_TENANT";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_TENANT" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "TENANT_CODE" VARCHAR(64 char) NULL,
    "DESCRIPTION" VARCHAR(255 char) NULL,
    "QUEUE_ID" INT NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_UDFS";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_UDFS" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NOT NULL,
    "FUNC_NAME" VARCHAR(255 char) NOT NULL,
    "CLASS_NAME" VARCHAR(255 char) NOT NULL,
    "TYPE" TINYINT NOT NULL,
    "ARG_TYPES" VARCHAR(255 char) NULL,
    "DATABASE" VARCHAR(255 char) NULL,
    "DESCRIPTION" VARCHAR(255 char) NULL,
    "RESOURCE_ID" INT NOT NULL,
    "RESOURCE_NAME" VARCHAR(255 char) NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_USER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_USER" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_NAME" VARCHAR(64 char) NULL,
    "USER_PASSWORD" VARCHAR(64 char) NULL,
    "USER_TYPE" TINYINT NULL,
    "EMAIL" VARCHAR(64 char) NULL,
    "PHONE" VARCHAR(11 char) NULL,
    "TENANT_ID" INT DEFAULT -1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    "QUEUE" VARCHAR(64 char) NULL,
    "STATE" TINYINT DEFAULT 1 NULL,
    "TIME_ZONE" VARCHAR(32 char) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_VERSION";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_VERSION" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "VERSION" VARCHAR(63 char) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255 char) NOT NULL,
    "ADDR_LIST" TEXT NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    "DESCRIPTION" TEXT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "VERSION" INT DEFAULT 1 NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "RELEASE_STATE" TINYINT NULL,
    "USER_ID" INT NULL,
    "GLOBAL_PARAMS" TEXT NULL,
    "FLAG" TINYINT NULL,
    "LOCATIONS" TEXT NULL,
    "WARNING_GROUP_ID" INT NULL,
    "TIMEOUT" INT DEFAULT 0 NULL,
    "EXECUTION_TYPE" TINYINT DEFAULT 0 NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "VERSION" INT DEFAULT 1 NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "RELEASE_STATE" TINYINT NULL,
    "USER_ID" INT NULL,
    "GLOBAL_PARAMS" TEXT NULL,
    "FLAG" TINYINT NULL,
    "LOCATIONS" TEXT NULL,
    "WARNING_GROUP_ID" INT NULL,
    "TIMEOUT" INT DEFAULT 0 NULL,
    "EXECUTION_TYPE" TINYINT DEFAULT 0 NULL,
    "OPERATOR" INT NULL,
    "OPERATE_TIME" TIMESTAMP(0) NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_VERSION" INT DEFAULT 1 NOT NULL,
    "PROJECT_CODE" BIGINT NULL,
    "STATE" TINYINT NULL,
    "STATE_HISTORY" TEXT NULL,
    "RECOVERY" TINYINT NULL,
    "START_TIME" TIMESTAMP(0) NULL,
    "END_TIME" TIMESTAMP(0) NULL,
    "RUN_TIMES" INT NULL,
    "HOST" VARCHAR(135 char) NULL,
    "COMMAND_TYPE" TINYINT NULL,
    "COMMAND_PARAM" TEXT NULL,
    "TASK_DEPEND_TYPE" TINYINT NULL,
    "MAX_TRY_TIMES" TINYINT DEFAULT 0 NULL,
    "FAILURE_STRATEGY" TINYINT DEFAULT 0 NULL,
    "WARNING_TYPE" TINYINT DEFAULT 0 NULL,
    "WARNING_GROUP_ID" INT NULL,
    "SCHEDULE_TIME" TIMESTAMP(0) NULL,
    "COMMAND_START_TIME" TIMESTAMP(0) NULL,
    "GLOBAL_PARAMS" TEXT NULL,
    "FLAG" TINYINT DEFAULT 1 NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "IS_SUB_WORKFLOW" INT DEFAULT 0 NULL,
    "EXECUTOR_ID" INT NOT NULL,
    "EXECUTOR_NAME" VARCHAR(64 char) NULL,
    "HISTORY_CMD" TEXT NULL,
    "WORKFLOW_INSTANCE_PRIORITY" INT DEFAULT 2 NULL,
    "WORKER_GROUP" VARCHAR(255 char) NULL,
    "ENVIRONMENT_CODE" BIGINT DEFAULT -1 NULL,
    "TIMEOUT" INT DEFAULT 0 NULL,
    "TENANT_CODE" VARCHAR(64 char) DEFAULT 'default' NULL,
    "VAR_POOL" CLOB NULL,
    "DRY_RUN" TINYINT DEFAULT 0 NULL,
    "NEXT_WORKFLOW_INSTANCE_ID" INT DEFAULT 0 NULL,
    "RESTART_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT DEFAULT 0 NOT NULL,
    "WORKFLOW_DEFINITION_VERSION" INT DEFAULT 0 NOT NULL,
    "TASK_DEFINITION_CODE" BIGINT DEFAULT 0 NOT NULL,
    "TASK_DEFINITION_VERSION" INT DEFAULT 0 NOT NULL,
    "DEPT_PROJECT_CODE" BIGINT DEFAULT 0 NOT NULL,
    "DEPT_WORKFLOW_DEFINITION_CODE" BIGINT DEFAULT 0 NOT NULL,
    "DEPT_TASK_DEFINITION_CODE" BIGINT DEFAULT 0 NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_VERSION" INT NOT NULL,
    "PRE_TASK_CODE" BIGINT NOT NULL,
    "PRE_TASK_VERSION" INT NOT NULL,
    "POST_TASK_CODE" BIGINT NOT NULL,
    "POST_TASK_VERSION" INT NOT NULL,
    "CONDITION_TYPE" TINYINT NULL,
    "CONDITION_PARAMS" TEXT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_VERSION" INT NOT NULL,
    "PRE_TASK_CODE" BIGINT NOT NULL,
    "PRE_TASK_VERSION" INT NOT NULL,
    "POST_TASK_CODE" BIGINT NOT NULL,
    "POST_TASK_VERSION" INT NOT NULL,
    "CONDITION_TYPE" TINYINT NULL,
    "CONDITION_PARAMS" TEXT NULL,
    "OPERATOR" INT NULL,
    "OPERATE_TIME" TIMESTAMP(0) NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE INDEX "IDX_GROUP_ID" ON "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE" ("GROUP_ID");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_GROUP_ID" VISIBLE;

CREATE INDEX "IDX_STATUS" ON "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE" ("STATUS");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_STATUS" VISIBLE;

CREATE INDEX "IDX_T_DS_TASK_GROUP_QUEUE_IN_QUEUE" ON "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE" ("IN_QUEUE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_T_DS_TASK_GROUP_QUEUE_IN_QUEUE" VISIBLE;

CREATE INDEX "IDX_TASK_ID" ON "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE" ("TASK_ID");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_TASK_ID" VISIBLE;

CREATE INDEX "IDX_WORKFLOW_INSTANCE_ID" ON "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE" ("WORKFLOW_INSTANCE_ID");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_WORKFLOW_INSTANCE_ID" VISIBLE;

CREATE INDEX "IDX_CODE_VERSION" ON "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE" (
    "TASK_CODE",
    "TASK_DEFINITION_VERSION"
);

ALTER INDEX "DOLPHINSCHEDULER"."IDX_CODE_VERSION" VISIBLE;

CREATE INDEX "WORKFLOW_INSTANCE_ID" ON "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE" ("WORKFLOW_INSTANCE_ID");

ALTER INDEX "DOLPHINSCHEDULER"."WORKFLOW_INSTANCE_ID" VISIBLE;

CREATE INDEX "START_TIME_INDEX" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE" (
    "START_TIME",
    "END_TIME"
);

ALTER INDEX "DOLPHINSCHEDULER"."START_TIME_INDEX" VISIBLE;

CREATE INDEX "WORKFLOW_INSTANCE_INDEX" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE" (
    "WORKFLOW_DEFINITION_CODE",
    "ID"
);

ALTER INDEX "DOLPHINSCHEDULER"."WORKFLOW_INSTANCE_INDEX" VISIBLE;

CREATE INDEX "IDX_DEPT_CODE" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE" (
    "DEPT_PROJECT_CODE",
    "DEPT_WORKFLOW_DEFINITION_CODE",
    "DEPT_TASK_DEFINITION_CODE"
);

ALTER INDEX "DOLPHINSCHEDULER"."IDX_DEPT_CODE" VISIBLE;

CREATE INDEX "IDX_TASK_CODE_VERSION" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE" (
    "TASK_DEFINITION_CODE",
    "TASK_DEFINITION_VERSION"
);

ALTER INDEX "DOLPHINSCHEDULER"."IDX_TASK_CODE_VERSION" VISIBLE;

CREATE INDEX "IDX_WORKFLOW_CODE_VERSION" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE" (
    "WORKFLOW_DEFINITION_CODE",
    "WORKFLOW_DEFINITION_VERSION"
);

ALTER INDEX "DOLPHINSCHEDULER"."IDX_WORKFLOW_CODE_VERSION" VISIBLE;

CREATE INDEX "IDX_CODE" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION" (
    "PROJECT_CODE",
    "WORKFLOW_DEFINITION_CODE"
);

ALTER INDEX "DOLPHINSCHEDULER"."IDX_CODE" VISIBLE;

CREATE INDEX "IDX_POST_TASK_CODE_VERSION" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION" (
    "POST_TASK_CODE",
    "POST_TASK_VERSION"
);

ALTER INDEX "DOLPHINSCHEDULER"."IDX_POST_TASK_CODE_VERSION" VISIBLE;

CREATE INDEX "IDX_PRE_TASK_CODE_VERSION" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION" (
    "PRE_TASK_CODE",
    "PRE_TASK_VERSION"
);

ALTER INDEX "DOLPHINSCHEDULER"."IDX_PRE_TASK_CODE_VERSION" VISIBLE;

CREATE INDEX "INDEX282737411479300" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG" (
    "WORKFLOW_DEFINITION_CODE",
    "WORKFLOW_DEFINITION_VERSION"
);

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282737411479300" VISIBLE;

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE_CONTEXT" ADD CONSTRAINT "TASK_INSTANCE_ID" UNIQUE ("TASK_INSTANCE_ID", "CONTEXT_TYPE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_TENANT" ADD CONSTRAINT "UNIQUE_TENANT_CODE" UNIQUE ("TENANT_CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_UDFS" ADD CONSTRAINT "UNIQUE_FUNC_NAME" UNIQUE ("FUNC_NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_USER" ADD CONSTRAINT "USER_NAME_UNIQUE" UNIQUE ("USER_NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_VERSION" ADD CONSTRAINT "VERSION_UNIQUE" UNIQUE ("VERSION");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP" ADD CONSTRAINT "NAME_UNIQUE" UNIQUE ("NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION" ADD CONSTRAINT "WORKFLOW_UNIQUE" UNIQUE ("NAME", "PROJECT_CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION" ADD CONSTRAINT "UNIQ_WORKFLOW_DEFINITION_CODE" UNIQUE ("CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG" ADD CONSTRAINT "UNIQ_IDX_CODE_VERSION" UNIQUE ("CODE", "VERSION");

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."FORCE_START" IS 'is force start 0 NO, 1 YES';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."GROUP_ID" IS 'taskGroup id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."IN_QUEUE" IS 'ready to get the queue by other task finish 0 NO, 1 YES';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."PRIORITY" IS 'priority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."STATUS" IS '-1: waiting 1: running 2: finished';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."TASK_ID" IS 'taskintanceid';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."TASK_NAME" IS 'TaskInstance name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP_QUEUE"."WORKFLOW_INSTANCE_ID" IS 'workflow instance id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."ALERT_FLAG" IS 'whether alert';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."APP_LINK" IS 'yarn app id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."CPU_QUOTA" IS 'cpuQuota(%): -1:Infinity';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."DELAY_TIME" IS 'task delay execution time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."DRY_RUN" IS 'dry run flag: 0 normal, 1 dry run';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."END_TIME" IS 'task end time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."ENVIRONMENT_CONFIG" IS 'this config contains many environment variables config';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."EXECUTE_PATH" IS 'task execute path in the host';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."FIRST_SUBMIT_TIME" IS 'task first submit time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."FLAG" IS '0 not available, 1 available';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."HOST" IS 'host of task running on';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."LOG_PATH" IS 'task log path';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."MAX_RETRY_TIMES" IS 'max retry times';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."MEMORY_MAX" IS 'MemoryMax(MB): -1:Infinity';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."NAME" IS 'task name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."PID" IS 'pid of task';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."RETRY_INTERVAL" IS 'retry interval when task failed ';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."RETRY_TIMES" IS 'task retry times';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."START_TIME" IS 'task start time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."STATE" IS 'Status: 0 commit succeeded, 1 running, 2 prepare to pause, 3 pause, 4 prepare to stop, 5 stop, 6 fail, 7 succeed, 8 need fault tolerance, 9 kill, 10 wait for thread, 11 wait for dependency to complete';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."SUBMIT_TIME" IS 'task submit time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."TASK_CODE" IS 'task definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."TASK_DEFINITION_VERSION" IS 'task definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."TASK_EXECUTE_TYPE" IS 'task execute type: 0-batch, 1-stream';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."TASK_GROUP_ID" IS 'task group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."TASK_INSTANCE_PRIORITY" IS 'task instance priority:0 Highest, 1 High, 2 Medium, 3 Low, 4 Lowest';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."TASK_PARAMS" IS 'job custom parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."TASK_TYPE" IS 'task type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."VAR_POOL" IS 'var_pool';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."WORKER_GROUP" IS 'worker group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."WORKFLOW_INSTANCE_ID" IS 'workflow instance id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE"."WORKFLOW_INSTANCE_NAME" IS 'workflow instance name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_INSTANCE_CONTEXT"."CONTEXT_TYPE" IS 'context type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TENANT"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TENANT"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TENANT"."QUEUE_ID" IS 'queue id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TENANT"."TENANT_CODE" IS 'tenant code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TENANT"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."ARG_TYPES" IS 'arguments types';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."CLASS_NAME" IS 'class of udf';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."DATABASE" IS 'data base';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."FUNC_NAME" IS 'UDF function name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."RESOURCE_ID" IS 'resource id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."RESOURCE_NAME" IS 'resource name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."TYPE" IS 'Udf function type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_UDFS"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."EMAIL" IS 'email';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."PHONE" IS 'phone';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."QUEUE" IS 'queue';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."STATE" IS 'state 0:disable 1:enable';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."TENANT_ID" IS 'tenant id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."TIME_ZONE" IS 'time zone';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."USER_NAME" IS 'user name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."USER_PASSWORD" IS 'user password';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_USER"."USER_TYPE" IS 'user type, 0:administrator，1:ordinary user';

COMMENT ON TABLE "DOLPHINSCHEDULER"."T_DS_VERSION" IS 'version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP"."ADDR_LIST" IS 'worker addr list. split by [, ]';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP"."DESCRIPTION" IS 'description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP"."ID" IS 'id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP"."NAME" IS 'worker group name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKER_GROUP"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."COMMAND_PARAM" IS 'json command parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."COMMAND_START_TIME" IS 'command start time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."COMMAND_TYPE" IS 'command type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."DRY_RUN" IS 'dry run flag：0 normal, 1 dry run';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."END_TIME" IS 'workflow instance end time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."EXECUTOR_ID" IS 'executor id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."EXECUTOR_NAME" IS 'execute user name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."FAILURE_STRATEGY" IS 'failure strategy. 0:end the workflow when node failed, 1:continue running the other nodes when node failed';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."FLAG" IS 'flag';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."GLOBAL_PARAMS" IS 'global parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."HISTORY_CMD" IS 'history commands of workflow instance operation';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."HOST" IS 'workflow instance host';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."IS_SUB_WORKFLOW" IS 'flag, whether the workflow is sub workflow';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."MAX_TRY_TIMES" IS 'max try times';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."NAME" IS 'workflow instance name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."NEXT_WORKFLOW_INSTANCE_ID" IS 'serial queue next workflowInstanceId';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."RECOVERY" IS 'workflow instance failover flag：0:normal, 1:failover instance';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."RESTART_TIME" IS 'workflow instance restart time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."RUN_TIMES" IS 'workflow instance run times';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."SCHEDULE_TIME" IS 'schedule time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."START_TIME" IS 'workflow instance start time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."STATE" IS 'workflow instance Status: 0 commit succeeded, 1 running, 2 prepare to pause, 3 pause, 4 prepare to stop, 5 stop, 6 fail, 7 succeed, 8 need fault tolerance, 9 kill, 10 wait for thread, 11 wait for dependency to complete';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."STATE_HISTORY" IS 'state history desc';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."TASK_DEPEND_TYPE" IS 'task depend type. 0: only current node, 1:before the node, 2:later nodes';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."TENANT_CODE" IS 'tenant code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."TIMEOUT" IS 'time out';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."VAR_POOL" IS 'var_pool';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."WARNING_GROUP_ID" IS 'warning group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."WARNING_TYPE" IS 'warning type. 0:no warning, 1:warning if workflow success, 2:warning if workflow failed, 3:warning if success';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."WORKER_GROUP" IS 'worker group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."WORKFLOW_DEFINITION_CODE" IS 'workflow definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."WORKFLOW_DEFINITION_VERSION" IS 'workflow definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_INSTANCE"."WORKFLOW_INSTANCE_PRIORITY" IS 'workflow instance priority. 0 Highest, 1 High, 2 Medium, 3 Low, 4 Lowest';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE"."DEPT_PROJECT_CODE" IS 'dependent project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE"."DEPT_TASK_DEFINITION_CODE" IS 'dependent task definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE"."DEPT_WORKFLOW_DEFINITION_CODE" IS 'dependent workflow definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_LINEAGE"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."CONDITION_PARAMS" IS 'condition params(json)';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."CONDITION_TYPE" IS 'condition type : 0 none, 1 judge 2 delay';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."ID" IS 'self-increasing id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."NAME" IS 'relation name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."POST_TASK_CODE" IS 'post task code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."POST_TASK_VERSION" IS 'post task version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."PRE_TASK_CODE" IS 'pre task code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."PRE_TASK_VERSION" IS 'pre task version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."WORKFLOW_DEFINITION_CODE" IS 'workflow code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION"."WORKFLOW_DEFINITION_VERSION" IS 'workflow version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."CONDITION_PARAMS" IS 'condition params(json)';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."CONDITION_TYPE" IS 'condition type : 0 none, 1 judge 2 delay';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."ID" IS 'self-increasing id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."NAME" IS 'relation name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."OPERATE_TIME" IS 'operate time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."OPERATOR" IS 'operator user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."POST_TASK_CODE" IS 'post task code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."POST_TASK_VERSION" IS 'post task version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."PRE_TASK_CODE" IS 'pre task code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."PRE_TASK_VERSION" IS 'pre task version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."WORKFLOW_DEFINITION_CODE" IS 'workflow code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_TASK_RELATION_LOG"."WORKFLOW_DEFINITION_VERSION" IS 'workflow version';

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_BLOB_TRIGGERS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_BLOB_TRIGGERS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "TRIGGER_NAME" VARCHAR(200 char) NOT NULL,
    "TRIGGER_GROUP" VARCHAR(200 char) NOT NULL,
    "BLOB_DATA" BLOB NULL,
    PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_CALENDARS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_CALENDARS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "CALENDAR_NAME" VARCHAR(200 char) NOT NULL,
    "CALENDAR" BLOB NOT NULL,
    PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_CRON_TRIGGERS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_CRON_TRIGGERS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "TRIGGER_NAME" VARCHAR(200 char) NOT NULL,
    "TRIGGER_GROUP" VARCHAR(200 char) NOT NULL,
    "CRON_EXPRESSION" VARCHAR(120 char) NOT NULL,
    "TIME_ZONE_ID" VARCHAR(80 char) NULL,
    PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "ENTRY_ID" VARCHAR(200 char) NOT NULL,
    "TRIGGER_NAME" VARCHAR(200 char) NOT NULL,
    "TRIGGER_GROUP" VARCHAR(200 char) NOT NULL,
    "INSTANCE_NAME" VARCHAR(200 char) NOT NULL,
    "FIRED_TIME" BIGINT NOT NULL,
    "SCHED_TIME" BIGINT NOT NULL,
    "PRIORITY" INT NOT NULL,
    "STATE" VARCHAR(16 char) NOT NULL,
    "JOB_NAME" VARCHAR(200 char) NULL,
    "JOB_GROUP" VARCHAR(200 char) NULL,
    "IS_NONCONCURRENT" VARCHAR(1 char) NULL,
    "REQUESTS_RECOVERY" VARCHAR(1 char) NULL,
    PRIMARY KEY ("SCHED_NAME", "ENTRY_ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_SIMPLE_TRIGGERS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_SIMPLE_TRIGGERS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "TRIGGER_NAME" VARCHAR(200 char) NOT NULL,
    "TRIGGER_GROUP" VARCHAR(200 char) NOT NULL,
    "REPEAT_COUNT" BIGINT NOT NULL,
    "REPEAT_INTERVAL" BIGINT NOT NULL,
    "TIMES_TRIGGERED" BIGINT NOT NULL,
    PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_SIMPROP_TRIGGERS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_SIMPROP_TRIGGERS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "TRIGGER_NAME" VARCHAR(200 char) NOT NULL,
    "TRIGGER_GROUP" VARCHAR(200 char) NOT NULL,
    "STR_PROP_1" VARCHAR(512 char) NULL,
    "STR_PROP_2" VARCHAR(512 char) NULL,
    "STR_PROP_3" VARCHAR(512 char) NULL,
    "INT_PROP_1" INT NULL,
    "INT_PROP_2" INT NULL,
    "LONG_PROP_1" BIGINT NULL,
    "LONG_PROP_2" BIGINT NULL,
    "DEC_PROP_1" DECIMAL(13, 4) NULL,
    "DEC_PROP_2" DECIMAL(13, 4) NULL,
    "BOOL_PROP_1" VARCHAR(1 char) NULL,
    "BOOL_PROP_2" VARCHAR(1 char) NULL,
    PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_TRIGGERS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "TRIGGER_NAME" VARCHAR(200 char) NOT NULL,
    "TRIGGER_GROUP" VARCHAR(200 char) NOT NULL,
    "JOB_NAME" VARCHAR(200 char) NOT NULL,
    "JOB_GROUP" VARCHAR(200 char) NOT NULL,
    "DESCRIPTION" VARCHAR(250 char) NULL,
    "NEXT_FIRE_TIME" BIGINT NULL,
    "PREV_FIRE_TIME" BIGINT NULL,
    "PRIORITY" INT NULL,
    "TRIGGER_STATE" VARCHAR(16 char) NOT NULL,
    "TRIGGER_TYPE" VARCHAR(8 char) NOT NULL,
    "START_TIME" BIGINT NOT NULL,
    "END_TIME" BIGINT NULL,
    "CALENDAR_NAME" VARCHAR(200 char) NULL,
    "MISFIRE_INSTR" SMALLINT NULL,
    "JOB_DATA" BLOB NULL,
    PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_JOB_DETAILS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_JOB_DETAILS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "JOB_NAME" VARCHAR(200 char) NOT NULL,
    "JOB_GROUP" VARCHAR(200 char) NOT NULL,
    "DESCRIPTION" VARCHAR(250 char) NULL,
    "JOB_CLASS_NAME" VARCHAR(250 char) NOT NULL,
    "IS_DURABLE" VARCHAR(1 char) NOT NULL,
    "IS_NONCONCURRENT" VARCHAR(1 char) NOT NULL,
    "IS_UPDATE_DATA" VARCHAR(1 char) NOT NULL,
    "REQUESTS_RECOVERY" VARCHAR(1 char) NOT NULL,
    "JOB_DATA" BLOB NULL,
    PRIMARY KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_LOCKS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_LOCKS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "LOCK_NAME" VARCHAR(40 char) NOT NULL,
    PRIMARY KEY ("SCHED_NAME", "LOCK_NAME")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_PAUSED_TRIGGER_GRPS";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_PAUSED_TRIGGER_GRPS" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "TRIGGER_GROUP" VARCHAR(200 char) NOT NULL,
    PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."QRTZ_SCHEDULER_STATE";
CREATE TABLE "DOLPHINSCHEDULER"."QRTZ_SCHEDULER_STATE" (
    "SCHED_NAME" VARCHAR(120 char) NOT NULL,
    "INSTANCE_NAME" VARCHAR(200 char) NOT NULL,
    "LAST_CHECKIN_TIME" BIGINT NOT NULL,
    "CHECKIN_INTERVAL" BIGINT NOT NULL,
    PRIMARY KEY ("SCHED_NAME", "INSTANCE_NAME")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NULL,
    "TOKEN" VARCHAR(64 char) NULL,
    "EXPIRE_TIME" TIMESTAMP(0) NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ALERT";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ALERT" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "TITLE" VARCHAR(512 char) NULL,
    "SIGN" CHAR(40 char) DEFAULT '' NOT NULL,
    "CONTENT" TEXT NULL,
    "ALERT_STATUS" TINYINT DEFAULT 0 NULL,
    "WARNING_TYPE" TINYINT DEFAULT 2 NULL,
    "LOG" TEXT NULL,
    "ALERTGROUP_ID" INT NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    "PROJECT_CODE" BIGINT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NULL,
    "WORKFLOW_INSTANCE_ID" INT NULL,
    "ALERT_TYPE" INT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ALERT_PLUGIN_INSTANCE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ALERT_PLUGIN_INSTANCE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "PLUGIN_DEFINE_ID" INT NOT NULL,
    "PLUGIN_INSTANCE_PARAMS" TEXT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "INSTANCE_NAME" VARCHAR(255 char) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ALERT_SEND_STATUS";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ALERT_SEND_STATUS" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "ALERT_ID" INT NOT NULL,
    "ALERT_PLUGIN_INSTANCE_ID" INT NOT NULL,
    "SEND_STATUS" TINYINT DEFAULT 0 NULL,
    "LOG" TEXT NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ALERTGROUP";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ALERTGROUP" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "ALERT_INSTANCE_IDS" VARCHAR(255 char) NULL,
    "CREATE_USER_ID" INT NULL,
    "GROUP_NAME" VARCHAR(255 char) NULL,
    "DESCRIPTION" VARCHAR(255 char) NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NOT NULL,
    "MODEL_ID" BIGINT NULL,
    "MODEL_NAME" VARCHAR(100 char) NULL,
    "MODEL_TYPE" VARCHAR(100 char) NOT NULL,
    "OPERATION_TYPE" VARCHAR(100 char) NOT NULL,
    "DESCRIPTION" VARCHAR(100 char) NULL,
    "LATENCY" INT NULL,
    "DETAIL" VARCHAR(100 char) NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_CLUSTER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_CLUSTER" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT NULL,
    "NAME" VARCHAR(255 char) NOT NULL,
    "CONFIG" TEXT NULL,
    "DESCRIPTION" TEXT NULL,
    "OPERATOR" INT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_COMMAND";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_COMMAND" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "COMMAND_TYPE" TINYINT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_VERSION" INT DEFAULT 0 NULL,
    "WORKFLOW_INSTANCE_ID" INT DEFAULT 0 NULL,
    "COMMAND_PARAM" TEXT NULL,
    "TASK_DEPEND_TYPE" TINYINT NULL,
    "FAILURE_STRATEGY" TINYINT DEFAULT 0 NULL,
    "WARNING_TYPE" TINYINT DEFAULT 0 NULL,
    "WARNING_GROUP_ID" INT NULL,
    "SCHEDULE_TIME" TIMESTAMP(0) NULL,
    "START_TIME" TIMESTAMP(0) NULL,
    "EXECUTOR_ID" INT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    "WORKFLOW_INSTANCE_PRIORITY" INT DEFAULT 2 NULL,
    "WORKER_GROUP" VARCHAR(255 char) NULL,
    "TENANT_CODE" VARCHAR(64 char) DEFAULT 'default' NULL,
    "ENVIRONMENT_CODE" BIGINT DEFAULT -1 NULL,
    "DRY_RUN" TINYINT DEFAULT 0 NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_DATASOURCE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_DATASOURCE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(64 char) NOT NULL,
    "NOTE" VARCHAR(255 char) NULL,
    "TYPE" TINYINT NOT NULL,
    "USER_ID" INT NOT NULL,
    "CONNECTION_PARAMS" TEXT NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT NULL,
    "NAME" VARCHAR(255 char) NOT NULL,
    "CONFIG" TEXT NULL,
    "DESCRIPTION" TEXT NULL,
    "OPERATOR" INT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT_WORKER_GROUP_RELATION";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT_WORKER_GROUP_RELATION" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "ENVIRONMENT_CODE" BIGINT NOT NULL,
    "WORKER_GROUP" VARCHAR(255 char) NOT NULL,
    "OPERATOR" INT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND" (
    "ID" INT NOT NULL,
    "COMMAND_TYPE" TINYINT NULL,
    "EXECUTOR_ID" INT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_VERSION" INT DEFAULT 0 NULL,
    "WORKFLOW_INSTANCE_ID" INT DEFAULT 0 NULL,
    "COMMAND_PARAM" TEXT NULL,
    "TASK_DEPEND_TYPE" TINYINT NULL,
    "FAILURE_STRATEGY" TINYINT DEFAULT 0 NULL,
    "WARNING_TYPE" TINYINT DEFAULT 0 NULL,
    "WARNING_GROUP_ID" INT NULL,
    "SCHEDULE_TIME" TIMESTAMP(0) NULL,
    "START_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    "WORKFLOW_INSTANCE_PRIORITY" INT DEFAULT 2 NULL,
    "WORKER_GROUP" VARCHAR(255 char) NULL,
    "TENANT_CODE" VARCHAR(64 char) DEFAULT 'default' NULL,
    "ENVIRONMENT_CODE" BIGINT DEFAULT -1 NULL,
    "MESSAGE" TEXT NULL,
    "DRY_RUN" TINYINT DEFAULT 0 NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_FAV_TASK";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_FAV_TASK" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "TASK_TYPE" VARCHAR(64 char) NOT NULL,
    "USER_ID" INT NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_CLIENT_HEARTBEAT";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_CLIENT_HEARTBEAT" (
    "ID" BIGINT NOT NULL,
    "CLIENT_NAME" VARCHAR(256 char) NOT NULL,
    "LAST_HEARTBEAT_TIME" BIGINT NOT NULL,
    "CONNECTION_CONFIG" TEXT NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "DATA_KEY" VARCHAR(256 char) NOT NULL,
    "DATA_VALUE" TEXT NOT NULL,
    "DATA_TYPE" VARCHAR(64 char) NOT NULL,
    "CLIENT_ID" BIGINT NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "LAST_UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA_CHANGE_EVENT";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA_CHANGE_EVENT" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "EVENT_TYPE" VARCHAR(64 char) NOT NULL,
    "JDBC_REGISTRY_DATA" TEXT NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "LOCK_KEY" VARCHAR(256 char) NOT NULL,
    "LOCK_OWNER" VARCHAR(256 char) NOT NULL,
    "CLIENT_ID" BIGINT NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_K8S";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_K8S" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "K8S_NAME" VARCHAR(255 char) NULL,
    "K8S_CONFIG" TEXT NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_K8S_NAMESPACE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_K8S_NAMESPACE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT DEFAULT 0 NOT NULL,
    "NAMESPACE" VARCHAR(255 char) NULL,
    "USER_ID" INT NULL,
    "CLUSTER_CODE" BIGINT DEFAULT 0 NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_PLUGIN_DEFINE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_PLUGIN_DEFINE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "PLUGIN_NAME" VARCHAR(255 char) NOT NULL,
    "PLUGIN_TYPE" VARCHAR(63 char) NOT NULL,
    "PLUGIN_PARAMS" TEXT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_PROJECT";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "CODE" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(255 char) NULL,
    "USER_ID" INT NULL,
    "FLAG" TINYINT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "PARAM_NAME" VARCHAR(255 char) NOT NULL,
    "PARAM_VALUE" TEXT NOT NULL,
    "PARAM_DATA_TYPE" VARCHAR(50 char) DEFAULT 'VARCHAR' NULL,
    "CODE" BIGINT NOT NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "USER_ID" INT NULL,
    "OPERATOR" INT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT NOT NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "PREFERENCES" VARCHAR(512 char) NOT NULL,
    "USER_ID" INT NULL,
    "STATE" INT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_QUEUE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_QUEUE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "QUEUE_NAME" VARCHAR(64 char) NULL,
    "QUEUE" VARCHAR(64 char) NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NOT NULL,
    "DATASOURCE_ID" INT NULL,
    "PERM" INT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NOT NULL,
    "NAMESPACE_ID" INT NULL,
    "PERM" INT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NOT NULL,
    "PROJECT_ID" INT NULL,
    "PERM" INT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "WORKER_GROUP" VARCHAR(255 char) NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_RESOURCES_USER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_RESOURCES_USER" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NOT NULL,
    "RESOURCES_ID" INT NULL,
    "PERM" INT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_SUB_WORKFLOW";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_SUB_WORKFLOW" (
    "ID" BIGINT AUTO_INCREMENT NOT NULL,
    "PARENT_WORKFLOW_INSTANCE_ID" BIGINT NOT NULL,
    "PARENT_TASK_CODE" BIGINT NOT NULL,
    "SUB_WORKFLOW_INSTANCE_ID" BIGINT NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "USER_ID" INT NOT NULL,
    "UDF_ID" INT NULL,
    "PERM" INT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "PARENT_WORKFLOW_INSTANCE_ID" INT NULL,
    "PARENT_TASK_INSTANCE_ID" INT NULL,
    "WORKFLOW_INSTANCE_ID" INT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_RESOURCES";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_RESOURCES" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "ALIAS" VARCHAR(64 char) NULL,
    "FILE_NAME" VARCHAR(64 char) NULL,
    "DESCRIPTION" VARCHAR(255 char) NULL,
    "USER_ID" INT NULL,
    "TYPE" TINYINT NULL,
    "SIZE" BIGINT NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    "PID" INT NULL,
    "FULL_NAME" VARCHAR(128 char) NULL,
    "IS_DIRECTORY" TINYINT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_SCHEDULES";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_SCHEDULES" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NOT NULL,
    "START_TIME" TIMESTAMP(0) NOT NULL,
    "END_TIME" TIMESTAMP(0) NOT NULL,
    "TIMEZONE_ID" VARCHAR(40 char) NULL,
    "CRONTAB" VARCHAR(255 char) NOT NULL,
    "FAILURE_STRATEGY" TINYINT NOT NULL,
    "USER_ID" INT NOT NULL,
    "RELEASE_STATE" TINYINT NOT NULL,
    "WARNING_TYPE" TINYINT NOT NULL,
    "WARNING_GROUP_ID" INT NULL,
    "WORKFLOW_INSTANCE_PRIORITY" INT DEFAULT 2 NULL,
    "WORKER_GROUP" VARCHAR(255 char) DEFAULT '' NULL,
    "TENANT_CODE" VARCHAR(64 char) DEFAULT 'default' NULL,
    "ENVIRONMENT_CODE" BIGINT DEFAULT -1 NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "WORKFLOW_DEFINITION_CODE" BIGINT NOT NULL,
    "WORKFLOW_DEFINITION_VERSION" INT NOT NULL,
    "WORKFLOW_INSTANCE_ID" BIGINT NOT NULL,
    "STATE" TINYINT DEFAULT 0 NOT NULL,
    "COMMAND" TEXT NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_SESSION";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_SESSION" (
    "ID" VARCHAR(64 char) NOT NULL,
    "USER_ID" INT NULL,
    "IP" VARCHAR(45 char) NULL,
    "LAST_LOGIN_TIME" TIMESTAMP(0) NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "VERSION" INT DEFAULT 1 NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "USER_ID" INT NULL,
    "TASK_TYPE" VARCHAR(50 char) NOT NULL,
    "TASK_EXECUTE_TYPE" INT DEFAULT 0 NULL,
    "TASK_PARAMS" CLOB NULL,
    "FLAG" TINYINT NULL,
    "TASK_PRIORITY" TINYINT DEFAULT 2 NULL,
    "WORKER_GROUP" VARCHAR(255 char) NULL,
    "ENVIRONMENT_CODE" BIGINT DEFAULT -1 NULL,
    "FAIL_RETRY_TIMES" INT NULL,
    "FAIL_RETRY_INTERVAL" INT NULL,
    "TIMEOUT_FLAG" TINYINT DEFAULT 0 NULL,
    "TIMEOUT_NOTIFY_STRATEGY" TINYINT NULL,
    "TIMEOUT" INT DEFAULT 0 NULL,
    "DELAY_TIME" INT DEFAULT 0 NULL,
    "RESOURCE_IDS" TEXT NULL,
    "TASK_GROUP_ID" INT NULL,
    "TASK_GROUP_PRIORITY" TINYINT DEFAULT 0 NULL,
    "CPU_QUOTA" INT DEFAULT -1 NOT NULL,
    "MEMORY_MAX" INT DEFAULT -1 NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID", "CODE")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "CODE" BIGINT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "VERSION" INT DEFAULT 1 NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "PROJECT_CODE" BIGINT NOT NULL,
    "USER_ID" INT NULL,
    "TASK_TYPE" VARCHAR(50 char) NOT NULL,
    "TASK_EXECUTE_TYPE" INT DEFAULT 0 NULL,
    "TASK_PARAMS" CLOB NULL,
    "FLAG" TINYINT NULL,
    "TASK_PRIORITY" TINYINT DEFAULT 2 NULL,
    "WORKER_GROUP" VARCHAR(255 char) NULL,
    "ENVIRONMENT_CODE" BIGINT DEFAULT -1 NULL,
    "FAIL_RETRY_TIMES" INT NULL,
    "FAIL_RETRY_INTERVAL" INT NULL,
    "TIMEOUT_FLAG" TINYINT DEFAULT 0 NULL,
    "TIMEOUT_NOTIFY_STRATEGY" TINYINT NULL,
    "TIMEOUT" INT DEFAULT 0 NULL,
    "DELAY_TIME" INT DEFAULT 0 NULL,
    "RESOURCE_IDS" TEXT NULL,
    "OPERATOR" INT NULL,
    "TASK_GROUP_ID" INT NULL,
    "TASK_GROUP_PRIORITY" TINYINT DEFAULT 0 NULL,
    "OPERATE_TIME" TIMESTAMP(0) NULL,
    "CPU_QUOTA" INT DEFAULT -1 NOT NULL,
    "MEMORY_MAX" INT DEFAULT -1 NOT NULL,
    "CREATE_TIME" TIMESTAMP(0) NOT NULL,
    "UPDATE_TIME" TIMESTAMP(0) NOT NULL,
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS "DOLPHINSCHEDULER"."T_DS_TASK_GROUP";
CREATE TABLE "DOLPHINSCHEDULER"."T_DS_TASK_GROUP" (
    "ID" INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(255 char) NULL,
    "DESCRIPTION" VARCHAR(255 char) NULL,
    "GROUP_SIZE" INT NOT NULL,
    "USE_SIZE" INT DEFAULT 0 NULL,
    "USER_ID" INT NULL,
    "PROJECT_CODE" BIGINT DEFAULT 0 NULL,
    "STATUS" TINYINT DEFAULT 1 NULL,
    "CREATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    "UPDATE_TIME" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NULL,
    PRIMARY KEY ("ID")
);

ALTER TABLE "DOLPHINSCHEDULER"."QRTZ_CRON_TRIGGERS" ADD CONSTRAINT "QRTZ_CRON_TRIGGERS_IBFK_1" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") WITH INDEX;

ALTER TABLE "DOLPHINSCHEDULER"."QRTZ_SIMPLE_TRIGGERS" ADD CONSTRAINT "QRTZ_SIMPLE_TRIGGERS_IBFK_1" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") WITH INDEX;

ALTER TABLE "DOLPHINSCHEDULER"."QRTZ_SIMPROP_TRIGGERS" ADD CONSTRAINT "QRTZ_SIMPROP_TRIGGERS_IBFK_1" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") WITH INDEX;

CREATE INDEX "SCHED_NAME" ON "DOLPHINSCHEDULER"."QRTZ_BLOB_TRIGGERS" ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."SCHED_NAME" VISIBLE;

CREATE INDEX "IDX_QRTZ_FT_INST_JOB_REQ_RCVRY" ON "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME","INSTANCE_NAME","REQUESTS_RECOVERY");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_FT_INST_JOB_REQ_RCVRY" VISIBLE;

CREATE INDEX "IDX_QRTZ_FT_J_G" ON "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME","JOB_NAME","JOB_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_FT_J_G" VISIBLE;

CREATE INDEX "IDX_QRTZ_FT_JG" ON "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME","JOB_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_FT_JG" VISIBLE;

CREATE INDEX "IDX_QRTZ_FT_T_G" ON "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_FT_T_G" VISIBLE;

CREATE INDEX "IDX_QRTZ_FT_TG" ON "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME","TRIGGER_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_FT_TG" VISIBLE;

CREATE INDEX "IDX_QRTZ_FT_TRIG_INST_NAME" ON "DOLPHINSCHEDULER"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME","INSTANCE_NAME");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_FT_TRIG_INST_NAME" VISIBLE;

CREATE INDEX "IDX_QRTZ_J_GRP" ON "DOLPHINSCHEDULER"."QRTZ_JOB_DETAILS" ("SCHED_NAME","JOB_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_J_GRP" VISIBLE;

CREATE INDEX "IDX_QRTZ_J_REQ_RECOVERY" ON "DOLPHINSCHEDULER"."QRTZ_JOB_DETAILS" ("SCHED_NAME","REQUESTS_RECOVERY");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_J_REQ_RECOVERY" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_C" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","CALENDAR_NAME");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_C" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_G" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_G" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_J" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","JOB_NAME","JOB_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_J" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_JG" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","JOB_GROUP");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_JG" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_N_G_STATE" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_GROUP","TRIGGER_STATE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_N_G_STATE" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_N_STATE" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP","TRIGGER_STATE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_N_STATE" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_NEXT_FIRE_TIME" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","NEXT_FIRE_TIME");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_NEXT_FIRE_TIME" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_NFT_MISFIRE" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","MISFIRE_INSTR","NEXT_FIRE_TIME");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_NFT_MISFIRE" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_NFT_ST" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_STATE","NEXT_FIRE_TIME");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_NFT_ST" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","MISFIRE_INSTR","NEXT_FIRE_TIME","TRIGGER_STATE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_NFT_ST_MISFIRE" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE_GRP" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","MISFIRE_INSTR","NEXT_FIRE_TIME","TRIGGER_GROUP","TRIGGER_STATE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_NFT_ST_MISFIRE_GRP" VISIBLE;

CREATE INDEX "IDX_QRTZ_T_STATE" ON "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_STATE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_QRTZ_T_STATE" VISIBLE;

CREATE INDEX "IDX_SIGN" ON "DOLPHINSCHEDULER"."T_DS_ALERT" ("SIGN");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_SIGN" VISIBLE;

CREATE INDEX "INDEX282738977364100" ON "DOLPHINSCHEDULER"."T_DS_ALERT" ("ALERT_STATUS");

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282738977364100" VISIBLE;

CREATE INDEX "PRIORITY_ID_INDEX" ON "DOLPHINSCHEDULER"."T_DS_COMMAND" ("WORKFLOW_INSTANCE_PRIORITY", "ID");

ALTER INDEX "DOLPHINSCHEDULER"."PRIORITY_ID_INDEX" VISIBLE;

CREATE INDEX "IDX_PARENT_TASK_CODE" ON "DOLPHINSCHEDULER"."T_DS_RELATION_SUB_WORKFLOW" ("PARENT_TASK_CODE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_PARENT_TASK_CODE" VISIBLE;

CREATE INDEX "IDX_PARENT_WORKFLOW_INSTANCE_ID" ON "DOLPHINSCHEDULER"."T_DS_RELATION_SUB_WORKFLOW" ("PARENT_WORKFLOW_INSTANCE_ID");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_PARENT_WORKFLOW_INSTANCE_ID" VISIBLE;

CREATE INDEX "IDX_SUB_WORKFLOW_INSTANCE_ID" ON "DOLPHINSCHEDULER"."T_DS_RELATION_SUB_WORKFLOW" ("SUB_WORKFLOW_INSTANCE_ID");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_SUB_WORKFLOW_INSTANCE_ID" VISIBLE;

CREATE INDEX "IDX_PARENT_WORKFLOW_TASK" ON "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE" ("PARENT_WORKFLOW_INSTANCE_ID","PARENT_TASK_INSTANCE_ID");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_PARENT_WORKFLOW_TASK" VISIBLE;

CREATE INDEX "INDEX282739037908000" ON "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE" ("WORKFLOW_INSTANCE_ID");

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282739037908000" VISIBLE;

CREATE INDEX "INDEX282739044908900" ON "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND" ("WORKFLOW_INSTANCE_ID");

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282739044908900" VISIBLE;

CREATE INDEX "IDX_PROJECT_CODE" ON "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION" ("PROJECT_CODE");

ALTER INDEX "DOLPHINSCHEDULER"."IDX_PROJECT_CODE" VISIBLE;

CREATE INDEX "INDEX282739061065200" ON "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG" ("CODE","VERSION");

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282739061065200" VISIBLE;

CREATE INDEX "INDEX282739066972700" ON "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG" ("PROJECT_CODE");

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282739066972700" VISIBLE;

CREATE INDEX "INDEX282739074042600" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION" ("PROJECT_CODE");

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282739074042600" VISIBLE;

CREATE INDEX "INDEX282739079976800" ON "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG" ("PROJECT_CODE");

ALTER INDEX "DOLPHINSCHEDULER"."INDEX282739079976800" VISIBLE;

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_ALERT_SEND_STATUS" ADD CONSTRAINT "ALERT_SEND_STATUS_UNIQUE" UNIQUE ("ALERT_ID", "ALERT_PLUGIN_INSTANCE_ID");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_ALERTGROUP" ADD CONSTRAINT "T_DS_ALERTGROUP_NAME_UN" UNIQUE ("GROUP_NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_CLUSTER" ADD CONSTRAINT "CLUSTER_NAME_UNIQUE" UNIQUE ("NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_CLUSTER" ADD CONSTRAINT "CLUSTER_CODE_UNIQUE" UNIQUE ("CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_DATASOURCE" ADD CONSTRAINT "T_DS_DATASOURCE_NAME_UN" UNIQUE ("NAME", "TYPE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT" ADD CONSTRAINT "ENVIRONMENT_NAME_UNIQUE" UNIQUE ("NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT" ADD CONSTRAINT "ENVIRONMENT_CODE_UNIQUE" UNIQUE ("CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT_WORKER_GROUP_RELATION" ADD CONSTRAINT "ENVIRONMENT_WORKER_GROUP_UNIQUE" UNIQUE ("ENVIRONMENT_CODE", "WORKER_GROUP");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA" ADD CONSTRAINT "UK_T_DS_JDBC_REGISTRY_DATAKEY" UNIQUE ("DATA_KEY");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK" ADD CONSTRAINT "UK_T_DS_JDBC_REGISTRY_LOCKKEY" UNIQUE ("LOCK_KEY");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_K8S_NAMESPACE" ADD CONSTRAINT "K8S_NAMESPACE_UNIQUE" UNIQUE ("NAMESPACE", "CLUSTER_CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_PLUGIN_DEFINE" ADD CONSTRAINT "T_DS_PLUGIN_DEFINE_UN" UNIQUE ("PLUGIN_NAME", "PLUGIN_TYPE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT" ADD CONSTRAINT "UNIQUE_NAME" UNIQUE ("NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT" ADD CONSTRAINT "UNIQUE_CODE" UNIQUE ("CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER" ADD CONSTRAINT "UNIQUE_PROJECT_PARAMETER_NAME" UNIQUE ("PROJECT_CODE", "PARAM_NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER" ADD CONSTRAINT "UNIQUE_PROJECT_PARAMETER_CODE" UNIQUE ("CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE" ADD CONSTRAINT "UNIQUE_PROJECT_PREFERENCE_PROJECT_CODE" UNIQUE ("PROJECT_CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE" ADD CONSTRAINT "UNIQUE_PROJECT_PREFERENCE_CODE" UNIQUE ("CODE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_QUEUE" ADD CONSTRAINT "UNIQUE_QUEUE_NAME" UNIQUE ("QUEUE_NAME");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER" ADD CONSTRAINT "NAMESPACE_USER_UNIQUE" UNIQUE ("USER_ID", "NAMESPACE_ID");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER" ADD CONSTRAINT "UNIQ_UID_PID" UNIQUE ("USER_ID", "PROJECT_ID");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP" ADD CONSTRAINT "UNIQUE_PROJECT_WORKER_GROUP" UNIQUE ("PROJECT_CODE", "WORKER_GROUP");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_RESOURCES" ADD CONSTRAINT "T_DS_RESOURCES_UN" UNIQUE ("FULL_NAME", "TYPE");

ALTER TABLE "DOLPHINSCHEDULER"."T_DS_SCHEDULES" ADD UNIQUE ("WORKFLOW_DEFINITION_CODE");

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN"."EXPIRE_TIME" IS 'end time of token ';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN"."TOKEN" IS 'token';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ACCESS_TOKEN"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."ALERT_STATUS" IS '0:wait running, 1:success, 2:failed';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."ALERT_TYPE" IS 'alert_type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."ALERTGROUP_ID" IS 'alert group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."CONTENT" IS 'Message content (can be email, can be SMS. Mail is stored in JSON map, and SMS is string)';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."LOG" IS 'log';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."PROJECT_CODE" IS 'project_code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."SIGN" IS 'sign=sha1(content)';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."TITLE" IS 'title';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."WARNING_TYPE" IS '1 workflow is successfully, 2 workflow/task is failed';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."WORKFLOW_DEFINITION_CODE" IS 'workflow_definition_code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT"."WORKFLOW_INSTANCE_ID" IS 'workflow_instance_id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT_PLUGIN_INSTANCE"."INSTANCE_NAME" IS 'alert instance name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT_PLUGIN_INSTANCE"."PLUGIN_INSTANCE_PARAMS" IS 'plugin instance params. Also contain the params value which user input in web ui.';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERT_SEND_STATUS"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERTGROUP"."ALERT_INSTANCE_IDS" IS 'alert instance ids';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERTGROUP"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERTGROUP"."CREATE_USER_ID" IS 'create user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERTGROUP"."GROUP_NAME" IS 'group name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERTGROUP"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ALERTGROUP"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."CREATE_TIME" IS 'operation time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."DESCRIPTION" IS 'api description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."DETAIL" IS 'object change detail';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."LATENCY" IS 'api cost milliseconds';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."MODEL_ID" IS 'model id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."MODEL_NAME" IS 'model name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."MODEL_TYPE" IS 'model type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."OPERATION_TYPE" IS 'operation type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_AUDIT_LOG"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_CLUSTER"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_CLUSTER"."CONFIG" IS 'this config contains many cluster variables config';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_CLUSTER"."DESCRIPTION" IS 'the details';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_CLUSTER"."ID" IS 'id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_CLUSTER"."NAME" IS 'cluster name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_CLUSTER"."OPERATOR" IS 'operator user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."COMMAND_PARAM" IS 'json command parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."COMMAND_TYPE" IS 'Command type: 0 start workflow, 1 start execution from current node, 2 resume fault-tolerant workflow, 3 resume pause workflow, 4 start execution from failed node, 5 complement, 6 schedule, 7 rerun, 8 pause, 9 stop, 10 resume waiting thread';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."DRY_RUN" IS 'dry run flag：0 normal, 1 dry run';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."EXECUTOR_ID" IS 'executor id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."FAILURE_STRATEGY" IS 'Failed policy: 0 end, 1 continue';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."SCHEDULE_TIME" IS 'schedule time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."START_TIME" IS 'start time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."TASK_DEPEND_TYPE" IS 'Node dependency type: 0 current node, 1 forward, 2 backward';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."TENANT_CODE" IS 'tenant code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."WARNING_GROUP_ID" IS 'warning group';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."WARNING_TYPE" IS 'Alarm type: 0 is not sent, 1 workflow is sent successfully, 2 workflow is sent failed, 3 workflow is sent successfully and all failures are sent';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."WORKER_GROUP" IS 'worker group';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."WORKFLOW_DEFINITION_CODE" IS 'workflow definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."WORKFLOW_DEFINITION_VERSION" IS 'workflow definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."WORKFLOW_INSTANCE_ID" IS 'workflow instance id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_COMMAND"."WORKFLOW_INSTANCE_PRIORITY" IS 'workflow instance priority: 0 Highest, 1 High, 2 Medium, 3 Low, 4 Lowest';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."CONNECTION_PARAMS" IS 'json connection params';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."NAME" IS 'data source name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."NOTE" IS 'description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."TYPE" IS 'data source type: 0:mysql, 1:postgresql, 2:hive, 3:spark';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_DATASOURCE"."USER_ID" IS 'the creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT"."CONFIG" IS 'this config contains many environment variables config';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT"."DESCRIPTION" IS 'the details';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT"."ID" IS 'id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT"."NAME" IS 'environment name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT"."OPERATOR" IS 'operator user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT_WORKER_GROUP_RELATION"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT_WORKER_GROUP_RELATION"."ID" IS 'id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT_WORKER_GROUP_RELATION"."OPERATOR" IS 'operator user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ENVIRONMENT_WORKER_GROUP_RELATION"."WORKER_GROUP" IS 'worker group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."COMMAND_PARAM" IS 'json command parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."COMMAND_TYPE" IS 'command type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."DRY_RUN" IS 'dry run flag: 0 normal, 1 dry run';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."EXECUTOR_ID" IS 'executor id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."FAILURE_STRATEGY" IS 'failure strategy';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."MESSAGE" IS 'message';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."SCHEDULE_TIME" IS 'scheduler time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."START_TIME" IS 'start time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."TASK_DEPEND_TYPE" IS 'task depend type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."TENANT_CODE" IS 'tenant code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."WARNING_GROUP_ID" IS 'warning group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."WARNING_TYPE" IS 'warning type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."WORKER_GROUP" IS 'worker group';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."WORKFLOW_DEFINITION_CODE" IS 'workflow definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."WORKFLOW_DEFINITION_VERSION" IS 'workflow definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."WORKFLOW_INSTANCE_ID" IS 'workflow instance id: 0';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_ERROR_COMMAND"."WORKFLOW_INSTANCE_PRIORITY" IS 'workflow instance priority, 0 Highest, 1 High, 2 Medium, 3 Low, 4 Lowest';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_FAV_TASK"."ID" IS 'id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_FAV_TASK"."TASK_TYPE" IS 'favorite task type name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_FAV_TASK"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_CLIENT_HEARTBEAT"."CLIENT_NAME" IS 'client name, ip_processId';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_CLIENT_HEARTBEAT"."CONNECTION_CONFIG" IS 'connection config';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_CLIENT_HEARTBEAT"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_CLIENT_HEARTBEAT"."ID" IS 'primary key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_CLIENT_HEARTBEAT"."LAST_HEARTBEAT_TIME" IS 'last heartbeat timestamp';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA"."CLIENT_ID" IS 'client id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA"."DATA_KEY" IS 'key, like zookeeper node path';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA"."DATA_TYPE" IS 'EPHEMERAL, PERSISTENT';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA"."DATA_VALUE" IS 'data, like zookeeper node value';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA"."ID" IS 'primary key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA"."LAST_UPDATE_TIME" IS 'last update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA_CHANGE_EVENT"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA_CHANGE_EVENT"."EVENT_TYPE" IS 'ADD, UPDATE, DELETE';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA_CHANGE_EVENT"."ID" IS 'primary key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_DATA_CHANGE_EVENT"."JDBC_REGISTRY_DATA" IS 'jdbc registry data';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK"."CLIENT_ID" IS 'client id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK"."ID" IS 'primary key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK"."LOCK_KEY" IS 'lock path';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_JDBC_REGISTRY_LOCK"."LOCK_OWNER" IS 'the lock owner, ip_processId';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_K8S"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_K8S"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_K8S_NAMESPACE"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_K8S_NAMESPACE"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PLUGIN_DEFINE"."PLUGIN_NAME" IS 'the name of plugin eg: email';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PLUGIN_DEFINE"."PLUGIN_PARAMS" IS 'plugin params';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PLUGIN_DEFINE"."PLUGIN_TYPE" IS 'plugin type . alert=alert plugin, job=job plugin';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."OPERATOR" IS 'operator user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."PARAM_DATA_TYPE" IS 'project parameter data type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."PARAM_NAME" IS 'project parameter name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."PARAM_VALUE" IS 'project parameter value';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PARAMETER"."USER_ID" IS 'creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."PREFERENCES" IS 'project preferences';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."STATE" IS '1 means enabled, 0 means disabled';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT_PREFERENCE"."USER_ID" IS 'creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_QUEUE"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_QUEUE"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_QUEUE"."QUEUE" IS 'yarn queue name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_QUEUE"."QUEUE_NAME" IS 'queue name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_QUEUE"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER"."DATASOURCE_ID" IS 'data source id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER"."PERM" IS 'limits of authority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_DATASOURCE_USER"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER"."NAMESPACE_ID" IS 'namespace id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER"."PERM" IS 'limits of authority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_NAMESPACE_USER"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER"."PERM" IS 'limits of authority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER"."PROJECT_ID" IS 'project id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_USER"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_PROJECT_WORKER_GROUP"."WORKER_GROUP" IS 'worker group';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_RESOURCES_USER"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_RESOURCES_USER"."PERM" IS 'limits of authority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_RESOURCES_USER"."RESOURCES_ID" IS 'resource id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_RESOURCES_USER"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_RESOURCES_USER"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER"."PERM" IS 'limits of authority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER"."UDF_ID" IS 'udf id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_UDFS_USER"."USER_ID" IS 'userid';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE"."PARENT_TASK_INSTANCE_ID" IS 'parent workflow instance id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE"."PARENT_WORKFLOW_INSTANCE_ID" IS 'parent workflow instance id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RELATION_WORKFLOW_INSTANCE"."WORKFLOW_INSTANCE_ID" IS 'child workflow instance id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."ALIAS" IS 'alias';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."FILE_NAME" IS 'file name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."SIZE" IS 'resource size';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."TYPE" IS 'resource type, 0:FILE，1:UDF';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_RESOURCES"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."CRONTAB" IS 'crontab description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."END_TIME" IS 'end time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."FAILURE_STRATEGY" IS 'failure strategy. 0:end, 1:continue';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."RELEASE_STATE" IS 'release state. 0:offline, 1:online ';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."START_TIME" IS 'start time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."TENANT_CODE" IS 'tenant code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."TIMEZONE_ID" IS 'schedule timezone id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."WARNING_GROUP_ID" IS 'alert group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."WARNING_TYPE" IS 'Alarm type: 0 is not sent, 1 workflow is sent successfully, 2 workflow is sent failed, 3 workflow is sent successfully and all failures are sent';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."WORKER_GROUP" IS 'worker group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."WORKFLOW_DEFINITION_CODE" IS 'workflow definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SCHEDULES"."WORKFLOW_INSTANCE_PRIORITY" IS 'workflow instance priority：0 Highest, 1 High, 2 Medium, 3 Low, 4 Lowest';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."COMMAND" IS 'command json';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."ID" IS 'primary key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."STATE" IS 'state of the serial queue: 0 waiting, 1 fired';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."WORKFLOW_DEFINITION_CODE" IS 'workflow definition code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."WORKFLOW_DEFINITION_VERSION" IS 'workflow definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SERIAL_COMMAND"."WORKFLOW_INSTANCE_ID" IS 'workflow instance id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SESSION"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SESSION"."IP" IS 'ip';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SESSION"."LAST_LOGIN_TIME" IS 'last login time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_SESSION"."USER_ID" IS 'user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."CPU_QUOTA" IS 'cpuQuota(%): -1:Infinity';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."DELAY_TIME" IS 'delay execution time, unit: minute';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."DESCRIPTION" IS 'description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."FAIL_RETRY_INTERVAL" IS 'failed retry interval';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."FAIL_RETRY_TIMES" IS 'number of failed retries';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."FLAG" IS '0 not available, 1 available';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."ID" IS 'self-increasing id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."MEMORY_MAX" IS 'MemoryMax(MB): -1:Infinity';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."NAME" IS 'task definition name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."RESOURCE_IDS" IS 'resource id, separated by comma';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TASK_EXECUTE_TYPE" IS 'task execute type: 0-batch, 1-stream';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TASK_GROUP_ID" IS 'task group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TASK_GROUP_PRIORITY" IS 'task group priority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TASK_PARAMS" IS 'job custom parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TASK_PRIORITY" IS 'job priority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TASK_TYPE" IS 'task type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TIMEOUT" IS 'timeout length, unit: minute';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TIMEOUT_FLAG" IS 'timeout flag:0 close, 1 open';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."TIMEOUT_NOTIFY_STRATEGY" IS 'timeout notification policy: 0 warning, 1 fail';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."USER_ID" IS 'task definition creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."VERSION" IS 'task definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION"."WORKER_GROUP" IS 'worker grouping';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."CPU_QUOTA" IS 'cpuQuota(%): -1:Infinity';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."DELAY_TIME" IS 'delay execution time, unit: minute';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."DESCRIPTION" IS 'description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."ENVIRONMENT_CODE" IS 'environment code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."FAIL_RETRY_INTERVAL" IS 'failed retry interval';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."FAIL_RETRY_TIMES" IS 'number of failed retries';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."FLAG" IS '0 not available, 1 available';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."ID" IS 'self-increasing id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."MEMORY_MAX" IS 'MemoryMax(MB): -1:Infinity';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."NAME" IS 'task definition name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."OPERATE_TIME" IS 'operate time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."OPERATOR" IS 'operator user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."RESOURCE_IDS" IS 'resource id, separated by comma';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TASK_EXECUTE_TYPE" IS 'task execute type: 0-batch, 1-stream';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TASK_GROUP_ID" IS 'task group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TASK_GROUP_PRIORITY" IS 'task group priority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TASK_PARAMS" IS 'job custom parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TASK_PRIORITY" IS 'job priority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TASK_TYPE" IS 'task type';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TIMEOUT" IS 'timeout length, unit: minute';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TIMEOUT_FLAG" IS 'timeout flag:0 close, 1 open';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."TIMEOUT_NOTIFY_STRATEGY" IS 'timeout notification policy: 0 warning, 1 fail';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."USER_ID" IS 'task definition creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."VERSION" IS 'task definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_DEFINITION_LOG"."WORKER_GROUP" IS 'worker grouping';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP"."GROUP_SIZE" IS 'group size';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP"."NAME" IS 'task_group name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP"."STATUS" IS '0 not available, 1 available';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP"."USE_SIZE" IS 'used size';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_TASK_GROUP"."USER_ID" IS 'creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."DESCRIPTION" IS 'description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."EXECUTION_TYPE" IS 'execution_type 0:parallel, 1:serial wait, 2:serial discard, 3:serial priority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."FLAG" IS '0 not available, 1 available';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."GLOBAL_PARAMS" IS 'global parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."ID" IS 'self-increasing id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."LOCATIONS" IS 'Node location information';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."NAME" IS 'workflow definition name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."RELEASE_STATE" IS 'workflow definition release state：0:offline, 1:online';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."TIMEOUT" IS 'time out, unit: minute';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."USER_ID" IS 'workflow definition creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."VERSION" IS 'workflow definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION"."WARNING_GROUP_ID" IS 'alert group id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."DESCRIPTION" IS 'description';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."EXECUTION_TYPE" IS 'execution_type 0:parallel, 1:serial wait, 2:serial discard, 3:serial priority';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."FLAG" IS '0 not available, 1 available';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."GLOBAL_PARAMS" IS 'global parameters';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."ID" IS 'self-increasing id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."LOCATIONS" IS 'Node location information';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."NAME" IS 'workflow definition name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."OPERATE_TIME" IS 'operate time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."OPERATOR" IS 'operator user id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."PROJECT_CODE" IS 'project code';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."RELEASE_STATE" IS 'workflow definition release state：0:offline, 1:online';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."TIMEOUT" IS 'time out, unit: minute';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."USER_ID" IS 'workflow definition creator id';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."VERSION" IS 'workflow definition version';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_WORKFLOW_DEFINITION_LOG"."WARNING_GROUP_ID" IS 'alert group id';

ALTER TABLE "DOLPHINSCHEDULER"."QRTZ_BLOB_TRIGGERS" ADD CONSTRAINT "QRTZ_BLOB_TRIGGERS_IBFK_1" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") WITH INDEX;

ALTER TABLE "DOLPHINSCHEDULER"."QRTZ_TRIGGERS" ADD CONSTRAINT "QRTZ_TRIGGERS_IBFK_1" FOREIGN KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "DOLPHINSCHEDULER"."QRTZ_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") WITH INDEX;

CREATE INDEX "USER_ID_INDEX" ON "DOLPHINSCHEDULER"."T_DS_PROJECT" ("USER_ID");

ALTER INDEX "DOLPHINSCHEDULER"."USER_ID_INDEX" VISIBLE;

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT"."CODE" IS 'encoding';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT"."CREATE_TIME" IS 'create time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT"."FLAG" IS '0 not available, 1 available';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT"."ID" IS 'key';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT"."NAME" IS 'project name';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT"."UPDATE_TIME" IS 'update time';

COMMENT ON COLUMN "DOLPHINSCHEDULER"."T_DS_PROJECT"."USER_ID" IS 'creator id';

INSERT INTO "DOLPHINSCHEDULER"."T_DS_TENANT"("ID","TENANT_CODE","DESCRIPTION","QUEUE_ID","CREATE_TIME","UPDATE_TIME") VALUES(-1,'default','default tenant',1,' 2026-05-14 18:04:47.000000000',' 2026-05-14 18:04:47.000000000');

INSERT INTO "DOLPHINSCHEDULER"."T_DS_USER"("ID","USER_NAME","USER_PASSWORD","USER_TYPE","EMAIL","PHONE","TENANT_ID","CREATE_TIME","UPDATE_TIME","QUEUE","STATE","TIME_ZONE") VALUES(1,'admin','7ad2410b2f4c074479a8937a28a22b8f',0,'xxx@qq.com','',-1,' 2026-05-14 18:04:47.000000000',' 2026-05-14 18:04:47.000000000',null,1,null);

INSERT INTO "DOLPHINSCHEDULER"."T_DS_VERSION"("ID","VERSION") VALUES(1,'3.4.1');

INSERT INTO "DOLPHINSCHEDULER"."T_DS_ALERTGROUP"("ID","ALERT_INSTANCE_IDS","CREATE_USER_ID","GROUP_NAME","DESCRIPTION","CREATE_TIME","UPDATE_TIME") VALUES(1,null,1,'default admin warning group','default admin warning group',' 2026-05-14 18:04:47.000000000',' 2026-05-14 18:04:47.000000000');

INSERT INTO "DOLPHINSCHEDULER"."T_DS_QUEUE"("ID","QUEUE_NAME","QUEUE","CREATE_TIME","UPDATE_TIME") VALUES(1,'default','default',null,null);
